### ISSUE TITLE
Bad Gitter url

### ISSUE THREAD

**Issue by vindarel** [40ants/40ants.github.com#2]
Hey, your Gitter url points to Coleslaw's repo. But I'd like a Gitter room to ping you there :)

**Comment by svetlyak40wt** [comment]
Yeah! I've finally created a CI config for CircleCI and now pull-request can be used to fix issues!

This issue I've already fixed in https://github.com/40ants/40ants.github.com/commit/c342ff7528a3834ac4cc52e2cd9ae391bcbfdef8 commit.
